df <- read.table("household_power_consumption.txt", sep = ";", header = TRUE, dec = ".", stringsAsFactors=FALSE)
subdf <- subset(df, Date %in% c("1/2/2007","2/2/2007"))
png("plot1.png", width=480, height=480)
hist(as.numeric(subdf$Global_active_power), freq = TRUE, main = "Global Active Power", xlab="Global Active Power (kilowatts)", col = "red")
dev.off()
